In [3]:
import numpy as np
import pandas as pd

In [83]:
!pip install pandas

  Using cached pandas-2.2.3-cp39-cp39-win_amd64.whl.metadata (19 kB)
  Using cached pytz-2025.1-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.2.3-cp39-cp39-win_amd64.whl (11.6 MB)
Using cached pytz-2025.1-py2.py3-none-any.whl (507 kB)
Using cached tzdata-2025.1-py2.py3-none-any.whl (346 kB)


## DİZİ KULLANIMI (Array Usage)

## 1)Dizi oluşturma( np.array() )

--Python’daki listeleri NumPy dizisine çevirmek için np.array() fonksiyonu kullanılır.

In [27]:
py_list = [1,2,3,4,5]

np_array = np.array(py_list)
np_array

array([1, 2, 3, 4, 5])

In [28]:
type(py_list), type(np_array)

(list, numpy.ndarray)

--NumPy dizileri, Python listelerine göre daha hızlı çalışır ve daha az bellek kullanır.

### Sıfırlardan Oluşan Dizi ( np.zeros() )

--np.zeros() fonksiyonu, istenilen boyutta tüm elemanları 0 olan bir NumPy dizisi oluşturur.

In [46]:
zeros = np.zeros((3,3))  # 3x3 boyutunda sıfır matrisi
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Birlerden Oluşan Dizi ( np.ones() )

--np.ones() fonksiyonu, istenilen boyutta tüm elemanları 1 olan bir NumPy dizisi oluşturur.

In [48]:
ones = np.ones((2,4))  # 2x4 boyutunda bir matrisi
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Belirtilen Aralıkta Sayılarla Dizi ( np.arange() )

--np.arange() fonksiyonu, belirli bir başlangıç, bitiş ve adım değerine göre dizi oluşturur.

In [49]:
arange_array = np.arange(0, 10, 2)  # 0'dan 10'a kadar 2 artarak git # 0 dahil edilir 10 dahil edilmez
print(arange_array)

[0 2 4 6 8]


### Belirtilen Aralığı Eşit Parçaya Bölme ( np.linspace() )

--np.linspace() fonksiyonu, başlangıç ve bitiş noktaları arasında eşit aralıklarla belirtilen sayıda değer oluşturur.

In [55]:
linspace_array = np.linspace(0,10,5) # 0 ile 10 arasında 5 eşit aralıklı sayı
print(linspace_array)

[ 0.   2.5  5.   7.5 10. ]


## 2)NumPy’de Temel İşlemler

### Toplama İşlemi (+)

In [60]:
arr = np.array([1, 2, 3, 4, 5])

# Her elemana 2 ekleme
result = arr + 2
print(result)

[3 4 5 6 7]


## Çıkarma İşlemi (-)

In [62]:
arr = np.array([1, 2, 3, 4, 5])

# Her elemandan 2 çıkarma
result = arr - 2
print(result)

[-1  0  1  2  3]


## Çarpma İşlemi (*)

In [63]:
arr = np.array([1, 2, 3, 4, 5])

# Her elemanı 2 ile çarpma
result = arr * 2
print(result)

[ 2  4  6  8 10]


## Bölme İşlemi(/)

In [65]:
arr = np.array([1,2,3,4,5])

# Her elemanı 2'ye bölme
result = arr / 2
print(result)

[0.5 1.  1.5 2.  2.5]


## Üs Alma İşlemi (**)

In [66]:
arr = np.array([1,2,3,4,5])

# Her elemanın 3 üssünü alma
result = arr ** 3
print(result)

[  1   8  27  64 125]


## Mod Alma İşlemi (%)

In [67]:
arr = np.array([1,2,3,4,5])

# Her elemanın 2'yle bölümünden kalanı bulma
result = arr % 2
print(result)

[1 0 1 0 1]


## Mutlak Değer (np.abs())

In [68]:
arr = np.array([-1, -2, 3, -4, 5])

# Negatif sayıları pozitif yapma
result = np.abs(arr)
print(result)

[1 2 3 4 5]


## Karşılaştırma İşlemleri 

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# 25'ten büyük olanları bul
result = arr > 25
print(result)

[False False  True  True  True]


## Matematiksel Fonksiyonlar

In [77]:
np.sqrt(arr)   # Karekök
np.exp(arr)    # Üstel (e^x)
np.log(arr)    # Doğal logaritma (ln)
np.sin(arr)    # Sinüs
np.cos(arr)    # Kosinüs
np.sum(arr)    # Toplam
np.mean(arr)   # Ortalama
np.median(arr) # Medyan
np.std(arr)    # Standart Sapma

np.float64(14.142135623730951)

## 3) Dizi Şekillendirme 

### Yeniden Şekillendirme (np.reshape())

--Bir NumPy dizisinin boyutlarını değiştirmek için reshape() fonksiyonu kullanılır.

In [90]:
arr = np.array([1, 2, 3, 4, 5, 6])

# 2 satır, 3 sütunluk bir matrise dönüştürme
reshaped = arr.reshape((2, 3))

pd.DataFrame(reshaped)

0  1  2
0  1  2  3
1  4  5  6

--Dizinin eleman sayısı değiştirilemez. Yani (2,3) boyutuna çevirdiğimizde 6 eleman olmalıdır.

## Düzleştirme (flatten())

--Çok boyutlu bir diziyi tek boyutlu hale getirmek için kullanılır.

In [ ]:
arr = np.array([[1,2,3], [4,5,6] [7,8,9]])

flattened_arr = arr.flatten()
print(flattened_arr)

[1 2 3 4 5 6]


##  Boyut Eklemek ((np.expand_dims())

--Var olan bir dizinin boyutunu artırmak için expand_dims() fonksiyonu kullanılır.

In [12]:
arr = np.array([1,2,3])

expanded = np.expand_dims(arr, axis=0)

print(arr,expanded)

[1 2 3] [[1 2 3]]


axis=0 → Yeni ekseni satır olarak (başta) ekler.

axis=1 → Yeni ekseni sütun olarak (ortada) ekler.

axis=-1 → Yeni ekseni en sona ekler.

In [6]:
arr = np.array([1,2,3])

expanded = np.expand_dims(arr, axis=1)
print(expanded)

[[1]
 [2]
 [3]]


In [13]:
arr = np.array([1,2,3])

expanded = np.expand_dims(arr, axis=-1)
print(expanded)

[[1]
 [2]
 [3]]


## Sıkıştırma (np.squeeze())

In [11]:
arr = np.array([[[1, 2, 3]]])  # 3 boyutlu dizi

squeezed = np.squeeze(arr)  

print(arr)
print(squeezed)

[[[1 2 3]]]
[1 2 3]


## Boyutları Değiştirme (np.resize())

--Eğer reshape() yerine resize() kullanırsanız, eleman sayısı yetmezse tekrar baştan başlatır.

In [121]:
arr = np.array([1, 2, 3, 4])

resized = np.resize(arr, (3, 3))

print(resized)

[[1 2 3]
 [4 1 2]
 [3 4 1]]


--reshape() hata verirken, resize() elemanları tekrar kullanır.